### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by JohnDorie** [BlockHorizons/InvSee#16]
Hi. 

Is the a Chance you can do a Alias like : /inv and /ec ?

Greetz

**Comment by Muqsit** [comment]
Hey @bermev2411
You can do this in your `pocketmine.yml`
```yaml
aliases:
  inv: [invsee]
  ec: [enderinvsee]
```
